./bin/datastruct.exe: ./obj/datatype-size.o
	g++ -g ./obj/datatype-size.o -o ./bin/datastruct.exe

./obj/datatype-size.o: ./src/datatype-size.cpp
	g++ -g ./src/datatype-size.cpp -o ./obj/datatype-size.o

clean:
	rm ./obj/*
	rm ./bin/*

full:
	echo "Not implemented"
